# Generated by Django 4.2.10 on 2024-03-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_things_alter_walking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='things',
            field=models.ManyToManyField(to='main_app.things'),
        ),
    ]
